# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-diaproteomics-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - anaconda::openjdk=8.0.152
  - r-base
  - openms-thirdparty=2.5.0
  - pyprophet=2.1.4
  - networkx
  - bioconda:easypqp=0.1.7
  - bioconductor-dialignr
